apiVersion: apps/v1
kind: Deployment
metadata:
  name: nft-bridge-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nft-bridge
  template:
    metadata:
      labels:
        app: nft-bridge
    spec:
      containers:
      - name: nft-bridge
        image: your-repo/nft-bridge:latest  # Replace with your image repository and tag
        ports:
        - containerPort: 3000  # Application runs on port 3000
        livenessProbe:
          httpGet:
            path: /health  # Adjust path if your app has a specific health check endpoint
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health  # Adjust path if your app has a specific health check endpoint
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nft-bridge-service
spec:
  selector:
    app: nft-bridge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000  # Maps port 80 to the app's port 3000
  type: ClusterIP
