name: Terraform Import Workflow

on:
   push:
    branches:
      - kk_assignment

jobs:
  terraform-import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5 # Update to your required Terraform version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Initialize Terraform
      run: |
        cd ./apps/nft-bridge/terraform  # Navigate to the Terraform directory
        terraform init

    - name: Add CloudWatch Log Group resource to Terraform
      run: |
        echo 'resource "aws_cloudwatch_log_group" "this" { name = "/aws/eks/default-eks-cluster/cluster" }' >> ./apps/nft-bridge/terraform/main.tf

    - name: Import CloudWatch Log Group
      run: |
        cd ./apps/nft-bridge/terraform
        terraform import aws_cloudwatch_log_group.this /aws/eks/default-eks-cluster/cluster

    - name: Import IAM Role
      run: |
        cd ./apps/nft-bridge/terraform
        terraform import aws_iam_role.node_role eks-node-group-role

    - name: Run Terraform Plan
      run: |
        cd ./apps/nft-bridge/terraform
        terraform plan