name: NFT Bridge CI/CD Pipeline

on:
  push:
    branches:
      - kk_assignment
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install
      working-directory: ./apps/nft-bridge

    - name: Fix Vulnerabilities
      run: npm audit fix --force
      working-directory: ./apps/nft-bridge

    - name: Install ESLint (if not already installed)
      run: npm install eslint --save-dev
      working-directory: ./apps/nft-bridge

    - name: Run Lint with Nx
      run: npx nx lint nft-bridge
      working-directory: .

    - name: Run Code Quality Check
      run: npm run lint
      working-directory: ./apps/nft-bridge

    # - name: Run Unit Tests
    #   run: npm test
    #   working-directory: ./apps/nft-bridge

    - name: Build Docker Image
      run: docker build -t nft-bridge:latest .
      working-directory: ./apps/nft-bridge

    # - name: Push Docker Image
    #   run: |
    #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #     docker tag nft-bridge:latest your-docker-registry/nft-bridge:latest
    #     docker push your-docker-registry/nft-bridge:latest
